import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';
import plugin from 'tailwindcss/plugin';
// filament tailwind settings
import preset from './vendor/filament/support/tailwind.config.preset';

/** @type {import('tailwindcss').Config} */
export default {
    // preset: [preset],
    darkMode: ['class', '[data-mode="dark"]'],
    content: [
        ...preset.content,
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './app/Filament/**/*.php',
        './resources/views/filament/**/*.blade.php',
        './vendor/filament/**/*.blade.php',
    ],
    important: false,
    safelist: [
        'bg-red-100',
        'bg-red-200',
        'bg-red-300',
        'bg-red-400',
        'bg-red-500',
        'bg-red-600',
        'bg-lime-100',
        'bg-lime-200',
        'bg-lime-300',
        'bg-lime-400',
        'bg-lime-500',
        'bg-lime-600',
        // Badge colors for ImageGalleriesTable
        'bg-blue-500',
        'bg-yellow-500',
        'bg-yellow-700',
        'bg-green-500',
        'bg-pink-500',
        'bg-purple-500',
    ],
    theme: {
        screens: {
            xs: "100%",
            sm: '540px',
            md: '720px	',
            lg: '960px',
            xl: '1140px',
            '2xl': '1320px',
        },
        container: {
            padding: '0.625rem',
        },
        fontFamily: {
            primary: ['Open Sans', 'sans-serif'],
            'ui-sans-serif': defaultTheme.fontFamily.sans,
        },
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
            spacing: {
                '0.5': '0.125rem',
                6: '1.5rem',
                7: '1.75rem',
                8: '2rem',
                15: '3.75rem',
            },
            fontSize: {
                '10': '0.781rem',
                '11': '0.86rem',
                '13': '1.016rem',
                base: '1.094rem',
                '15': '1.172rem',
                '16': '1.25rem',
                '17': '1.329rem',
                '19': '1.485rem',
                '21': '1.641rem',
                '22': '1.719rem',
            },
            colors: {
                ...preset.theme.extend.colors,
                mandarin: {
                    50:  '#FFF8F0',
                    100: '#FFEBD9',
                    200: '#FFD0A6',
                    300: '#FFB36E',
                    400: '#FF9743',
                    500: '#FF7C1A',
                    600: '#DB600F',
                    700: '#B7450A',
                    800: '#933606',
                    900: '#7A2C04',
                }
                ,
                gray: {
                    50: '#E6E6EB',
                    100: '#D9DAE0',
                    200: '#C0C2CB',
                    300: '#A7A9B6',
                    400: '#8D91A2',
                    500: '#74788D',
                    600: '#5F6273',
                    700: '#3F414D',
                    800: '#2A2C33',
                    900: '#202126',
                },
                green: {
                    50: '#CAEDDF',
                    100: '#B2E4D0',
                    200: '#8BD7B8',
                    300: '#64C9A0',
                    400: '#3DBC89',
                    500: '#2ab57d',
                    600: '#229466',
                    700: '#1F845B',
                    800: '#176344',
                    900: '#0F422D',
                },
                lime: {
                    50: '#e5f9e0',
                    100: '#d9f7dc',
                    200: '#aadf8a',
                    300: '#7fca62',
                    400: '#56b542',
                    500: '#389f2e',
                    600: '#87e291',
                    700: '#2cf290',
                    800: '#227721',
                    900: '#1a6319',
                },
                sky: {
                    50: '#D2E9FB',
                    100: '#BEDFF9',
                    200: '#9DCEF6',
                    300: '#7CBEF3',
                    400: '#5BAEF0',
                    500: '#4BA6EF',
                    600: '#4497D9',
                    700: '#3D88C4',
                    800: '#306A98',
                    900: '#295B82',
                },
                yellow: {
                    50: '#FFF0D4',
                    100: '#FFE2B1',
                    200: '#FFD692',
                    300: '#FFD082',
                    400: '#FFC563',
                    500: '#ffbf53',
                    600: '#E8AE4B',
                    700: '#D19C44',
                    800: '#B98B3C',
                    900: '#A27A35',
                },
                red: {
                    50: '#FEDCDB',
                    100: '#e5e5e5',
                    200: '#FEB8B6',
                    300: '#FE8D8A',
                    400: '#FD706D',
                    500: '#FD625E',
                    600: '#E65955',
                    700: '#CF504D',
                    800: '#B84744',
                    900: '#A13E3C',
                },
                neutral: {
                    50: '#DCDCDC',
                    100: '#CCCCCC',
                    200: '#B3B3B3',
                    300: '#999999',
                    400: '#808080',
                    500: '#737373',
                    600: '#545454',
                    700: '#3F3F3F',
                    800: '#2A2A2A',
                    900: '#1F1F1F',
                },
                zinc: {
                    50: '#B2B3B2',
                    100: '#ADB5BD',
                    200: '#919392',
                    300: '#858786',
                    400: '#666867',
                    500: '#525654',
                    600: '#3F4341',
                    700: '#363A38',
                    800: '#2c302e',
                    900: '#242726',
                },
            },
        },
    },
    plugins: [
        forms, typography,
        plugin(function ({ addBase, theme }) {
            addBase({
                'h1': { fontSize: theme('fontSize.4xl'), fontWeight: theme('fontWeight.semibold'), fontFamily: theme('fontFamily.primary') },
                'h2': { fontSize: theme('fontSize.3xl'), fontWeight: theme('fontWeight.semibold'), fontFamily: theme('fontFamily.primary') },
                'h3': { fontSize: theme('fontSize.2xl'), fontWeight: theme('fontWeight.semibold'), fontFamily: theme('fontFamily.primary') },
                'h4': { fontSize: theme('fontSize.xl'), fontWeight: theme('fontWeight.semibold'), fontFamily: theme('fontFamily.primary') },
                'h5': { fontSize: theme('fontSize.lg'), fontWeight: theme('fontWeight.semibold'), fontFamily: theme('fontFamily.primary') },
                'h6': { fontSize: theme('fontSize.base'), fontWeight: theme('fontWeight.semibold'), fontFamily: theme('fontFamily.primary') },
            })
        }),
        plugin(function ({ addComponents, theme }) {
            addComponents({
                '.btn': {
                    padding: '0.4375rem 0.75rem',
                    borderRadius: '0.30rem',
                    fontWeight: theme('fontWeight.normal'),
                    fontSize: '0.875rem',
                    display: 'inline-block',
                    borderWidth: '1px',
                    borderStyle: 'solid',
                    textAlign: 'center',
                    transition: 'all 0.5s ease',
                },
                '.card': {
                    borderStyle: 'solid',
                    borderColor: '#FF7C1A',
                    marginBottom: theme('margin.5'),
                    borderRadius: '25px',
                    border: '1px solid #FF7C1A',
                    backgroundColor: '#ffffff',
                },
                '.card-body': {
                    padding: theme('padding.5'),
                }
            })
        })
    ],
};
