<?php

namespace Modules\API\Resources\Content;

use OpenApi\Annotations as OA;

/**
 * @OA\Schema(
 *   schema="ContentSearchResponse",
 *   title="Content Search Response",
 *   description="Schema Content Search Response",
 *   type="object",
 *   required={"success", "data"},
 *   @OA\Property(
 *     property="success",
 *     type="boolean",
 *     description="Success status.",
 *     example=true
 *   ),
 *   @OA\Property(
 *     property="data",
 *     type="object",
 *     description="Data.",
 *     @OA\Property(
 *       property="count",
 *       type="integer",
 *       description="Total number of results.",
 *       example=1364
 *     ),
 *     @OA\Property(
 *       property="query",
 *       type="object",
 *       description="Query.",
 *       @OA\Property(
 *         property="rating",
 *         type="integer",
 *         description="Rating of the hotel.",
 *         example=1
 *       ),
 *       @OA\Property(
 *         property="page",
 *         type="integer",
 *         description="Page number.",
 *         example=1
 *       ),
 *       @OA\Property(
 *         property="results_per_page",
 *         type="integer",
 *         description="Number of results per page.",
 *         example=20
 *       ),
 *       @OA\Property(
 *         property="latitude",
 *         type="number",
 *         description="Latitude.",
 *         example=40.748
 *       ),
 *       @OA\Property(
 *         property="longitude",
 *         type="number",
 *         description="Longitude.",
 *         example=-73.991
 *       ),
 *       @OA\Property(
 *         property="radius",
 *         type="integer",
 *         description="Radius of the search area in kilometers.",
 *         example=20
 *       )
 *     ),
 *     @OA\Property(
 *       property="results",
 *       type="object",
 *       description="Results.",
 *       @OA\Property(
 *         property="Expedia",
 *         type="array",
 *         description="Expedia.",
 *         @OA\Items(
 *           type="object",
 *           @OA\Property(
 *             property="giata_hotel_code",
 *             type="integer",
 *             description="Giata hotel code.",
 *             example=60295986
 *           ),
 *           @OA\Property(
 *             property="images",
 *             type="array",
 *             description="Images.",
 *             @OA\Items(
 *               type="string",
 *               example="https://i.travelapi.com/lodging/1000000/10000/100/87/cce95a1e_b.jpg"
 *             )
 *           ),
 *           @OA\Property(
 *             property="description",
 *             type="string",
 *             description="Description.",
 *             example=""
 *           ),
 *           @OA\Property(
 *             property="hotel_name",
 *             type="string",
 *             description="Hotel name.",
 *             example="Sheraton New York Times Square Hotel"
 *           ),
 *           @OA\Property(
 *             property="distance",
 *             type="string",
 *             description="Distance.",
 *             example=""
 *           ),
 *           @OA\Property(
 *             property="latitude",
 *             type="string",
 *             description="Latitude.",
 *             example="40.76264"
 *           ),
 *           @OA\Property(
 *             property="longitude",
 *             type="string",
 *             description="Longitude.",
 *             example="-73.98213"
 *           ),
 *           @OA\Property(
 *             property="rating",
 *             type="string",
 *             description="Rating.",
 *             example="4"
 *           ),
 *           @OA\Property(
 *             property="amenities",
 *             type="array",
 *             description="Amenities.",
 *             @OA\Items(
 *               type="string",
 *               example="Elevator"
 *             )
 *           ),
 *           @OA\Property(
 *             property="giata_destination",
 *             type="string",
 *             description="Giata destination.",
 *             example="New York"
 *           ),
 *           @OA\Property(
 *             property="user_rating",
 *             type="string",
 *             description="User rating.",
 *             example="4"
 *           ),
 *           @OA\Property(
 *             property="weight",
 *             type="integer",
 *             description="Weight.",
 *             example=0
 *           )
 *         )
 *       )
 *     )
 *   ) 
 * ),
 * @OA\Examples(
 *     example="ContentSearchResponse",
 *     summary="Example Content Search Response",
 *     value=
  * {
 * 	"success": true,
 * 	"data": {
 * 	  "count": 1364,
 * 	  "query": {
 * 		"rating": 1,
 * 		"page": 1,
 * 		"results_per_page": 20,
 * 		"latitude": 40.748,
 * 		"longitude": -73.991,
 * 		"radius": 20
 * 	  },
 * 	  "results": {
 * 		"Expedia": {
 * 		  {
 * 			"giata_hotel_code": 60295986,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/100/87/cce95a1e_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/100/87/29ac8070_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/100/87/d5e3cf28_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/100/87/9a71decb_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/100/87/701d1ecb_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Sheraton New York Times Square Hotel",
 * 			"distance": "",
 * 			"latitude": "40.76264",
 * 			"longitude": "-73.98213",
 * 			"rating": "4",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "ATM/banking",
 * 			  "Concierge services",
 * 			  "Gift shops or newsstand",
 * 			  "Shopping on site",
 * 			  "Conference space",
 * 			  "Breakfast available (surcharge)",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "24-hour front desk",
 * 			  "Business center",
 * 			  "Porter/bellhop",
 * 			  "Express check-out",
 * 			  "Dry cleaning/laundry service",
 * 			  "Smoke-free property",
 * 			  "Wedding services",
 * 			  "Express check-in",
 * 			  "Grocery/convenience store",
 * 			  "Free WiFi",
 * 			  "Wheelchair accessible path of travel",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "Wheelchair accessible parking",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Braille or raised signage",
 * 			  "Number of restaurants - 1",
 * 			  "Conference space size (feet) - 36000",
 * 			  "Conference space size (meters) - 3344",
 * 			  "Number of meeting rooms - 33",
 * 			  "Conference center",
 * 			  "Snack bar/deli",
 * 			  "Self parking (surcharge)",
 * 			  "Number of bars/lounges - 1",
 * 			  "Number of coffee shops/cafes - 1",
 * 			  "Luggage storage",
 * 			  "24-hour fitness facilities",
 * 			  "Ballroom",
 * 			  "LED light bulbs",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Wheelchair-accessible public washroom",
 * 			  "Wheelchair-accessible concierge desk",
 * 			  "Valet for wheelchair-equipped vehicle",
 * 			  "Wheelchair-accessible path to elevator",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible fitness center",
 * 			  "Wheelchair-accessible meeting spaces/business center",
 * 			  "Wheelchair-accessible on-site restaurant",
 * 			  "Wheelchair-accessible lounge",
 * 			  "Visual alarms in hallways",
 * 			  "Handrails in stairways",
 * 			  "Well-lit path to entrance",
 * 			  "No accessible shuttle",
 * 			  "Number of accessible parking spaces - 10"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "4",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 23356833,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/600/562/197d6c20_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/600/562/e69c591d_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/600/562/091085fd_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/600/562/5f7cab65_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/600/562/d2c77c6e_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Howard Johnson by Wyndham Clifton NJ",
 * 			"distance": "",
 * 			"latitude": "40.83517",
 * 			"longitude": "-74.150047",
 * 			"rating": "2",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "ATM/banking",
 * 			  "Shopping on site",
 * 			  "Conference space",
 * 			  "Golfing nearby",
 * 			  "Coffee/tea in common areas",
 * 			  "Laundry facilities",
 * 			  "Garden",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "Free newspapers in lobby",
 * 			  "24-hour front desk",
 * 			  "Business center",
 * 			  "Dry cleaning/laundry service",
 * 			  "Grocery/convenience store",
 * 			  "Free WiFi",
 * 			  "Wheelchair accessible parking",
 * 			  "Braille or raised signage",
 * 			  "24-hour business center",
 * 			  "Conference space size (feet) - 900",
 * 			  "Conference space size (meters) - 84",
 * 			  "Number of meeting rooms - 1",
 * 			  "RV, bus, truck parking",
 * 			  "Bicycle rentals on site",
 * 			  "Free self parking",
 * 			  "Luggage storage",
 * 			  "Electric car charging station",
 * 			  "Vegetable garden",
 * 			  "Eco-friendly cleaning products provided",
 * 			  "Eco-friendly toiletries",
 * 			  "LED light bulbs",
 * 			  "Recycling",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Assistive listening devices in meeting rooms",
 * 			  "Wheelchair-accessible van parking",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible meeting spaces/business center",
 * 			  "Wheelchair-accessible on-site restaurant",
 * 			  "Change of towels (on request)",
 * 			  "Change of bed sheets (on request)",
 * 			  "Vegetarian breakfast available",
 * 			  "Organic food",
 * 			  "Humane animal treatment",
 * 			  "Locally-owned & organized tours & activities",
 * 			  "Showcase for local artists",
 * 			  "Sustainability/community reinvestment (10% revenue or more)",
 * 			  "Locally-sourced food on site (80% or more)",
 * 			  "Energy-saving switches",
 * 			  "At least 80% of all lighting comes from LEDs",
 * 			  "Comprehensive food waste policy",
 * 			  "Vegan menu options available",
 * 			  "Vegetarian menu options available",
 * 			  "Comprehensive recycling policy",
 * 			  "No single-use plastic soda bottles",
 * 			  "No single-use plastic stirrers",
 * 			  "Biodegradable/compostable stirrers",
 * 			  "No single-use plastic straws",
 * 			  "Biodegradable/compostable straws",
 * 			  "Reusable cups only",
 * 			  "Reusable tableware only",
 * 			  "Water-efficient showers only",
 * 			  "No accessible shuttle"
 * 			},
 * 			"giata_destination": "Clifton",
 * 			"user_rating": "2",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 60046066,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/700/643/69374200_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/700/643/708da67b_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/700/643/5c284df2_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/700/643/0023980e_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/700/643/57aa6e02_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Hilton Hasbrouck Heights/Meadowlands",
 * 			"distance": "",
 * 			"latitude": "40.87231",
 * 			"longitude": "-74.06221",
 * 			"rating": "3.5",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "ATM/banking",
 * 			  "Concierge services",
 * 			  "Gift shops or newsstand",
 * 			  "Conference space",
 * 			  "Coffee/tea in common areas",
 * 			  "Breakfast available (surcharge)",
 * 			  "Laundry facilities",
 * 			  "Television in common areas",
 * 			  "Garden",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "Free newspapers in lobby",
 * 			  "24-hour front desk",
 * 			  "Business center",
 * 			  "Porter/bellhop",
 * 			  "Express check-out",
 * 			  "Dry cleaning/laundry service",
 * 			  "Smoke-free property",
 * 			  "Use of nearby fitness center (discount)",
 * 			  "WiFi (surcharge)",
 * 			  "Free train station pickup",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "Wheelchair accessible parking",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Braille or raised signage",
 * 			  "Free area shuttle",
 * 			  "Number of restaurants - 1",
 * 			  "Conference space size (feet) - 23002",
 * 			  "Conference space size (meters) - 2137",
 * 			  "Number of meeting rooms - 14",
 * 			  "Conference center",
 * 			  "Bicycle rentals on site",
 * 			  "Free self parking",
 * 			  "Computer station",
 * 			  "Number of bars/lounges - 1",
 * 			  "Number of coffee shops/cafes - 1",
 * 			  "Free RV, bus, truck parking",
 * 			  "24-hour fitness facilities",
 * 			  "Terrace",
 * 			  "Free train station drop-off",
 * 			  "Electric car charging station",
 * 			  "Shared microwave",
 * 			  "Water dispenser",
 * 			  "Housekeeping on request",
 * 			  "Vegetable garden",
 * 			  "Banquet hall",
 * 			  "Eco-friendly cleaning products provided",
 * 			  "Eco-friendly toiletries",
 * 			  "LED light bulbs",
 * 			  "Recycling",
 * 			  "Grey water recycling system",
 * 			  "Off-street parking",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Wheelchair-accessible van parking",
 * 			  "Wheelchair-accessible path to elevator",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible fitness center",
 * 			  "Wheelchair-accessible meeting spaces/business center",
 * 			  "Wheelchair-accessible on-site restaurant",
 * 			  "Change of towels (on request)",
 * 			  "Change of bed sheets (on request)",
 * 			  "Well-lit path to entrance",
 * 			  "Stair-free path to entrance",
 * 			  "Vegetarian breakfast available",
 * 			  "Organic food",
 * 			  "Annual carbon offsets",
 * 			  "Humane animal treatment",
 * 			  "Locally-owned & organized tours & activities",
 * 			  "Showcase for local artists",
 * 			  "Sustainability/community reinvestment (10% revenue or more)",
 * 			  "Guest education on local ecosystems and culture",
 * 			  "Double-glazing on all windows",
 * 			  "Locally-sourced food on site (80% or more)",
 * 			  "Energy-saving switches",
 * 			  "At least 80% of all lighting comes from LEDs",
 * 			  "Comprehensive food waste policy",
 * 			  "Vegan menu options available",
 * 			  "Vegetarian menu options available",
 * 			  "Comprehensive recycling policy",
 * 			  "No single-use plastic soda bottles",
 * 			  "No single-use plastic stirrers",
 * 			  "Biodegradable/compostable stirrers",
 * 			  "No single-use plastic straws",
 * 			  "Biodegradable/compostable straws",
 * 			  "No single-use plastic water bottles",
 * 			  "Reusable cups only",
 * 			  "Reusable tableware only",
 * 			  "Water-efficient showers only"
 * 			},
 * 			"giata_destination": "Hasbrouck Heights",
 * 			"user_rating": "3.5",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 13512226,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/800/758/e6c67431_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/800/758/88177fab_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/800/758/d73bb58c_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/800/758/2085de58_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/800/758/c7daa611_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Stewart Hotel",
 * 			"distance": "",
 * 			"latitude": "40.74892",
 * 			"longitude": "-73.99218",
 * 			"rating": "4",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "Hair salon",
 * 			  "ATM/banking",
 * 			  "Concierge services",
 * 			  "Breakfast available (surcharge)",
 * 			  "Laundry facilities",
 * 			  "Television in common areas",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "Free newspapers in lobby",
 * 			  "24-hour front desk",
 * 			  "Business center",
 * 			  "Porter/bellhop",
 * 			  "Express check-out",
 * 			  "Dry cleaning/laundry service",
 * 			  "Internet access - wireless",
 * 			  "Internet access in public areas - high speed",
 * 			  "Meeting rooms",
 * 			  "Smoke-free property",
 * 			  "Wedding services",
 * 			  "Tours/ticket assistance",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Braille or raised signage",
 * 			  "Area shuttle (surcharge)",
 * 			  "Number of restaurants - 1",
 * 			  "24-hour business center",
 * 			  "Self parking (surcharge)",
 * 			  "Valet parking (surcharge)",
 * 			  "Number of bars/lounges - 1",
 * 			  "Number of coffee shops/cafes - 1",
 * 			  "Luggage storage",
 * 			  "24-hour fitness facilities",
 * 			  "Ballroom",
 * 			  "Banquet hall",
 * 			  "Eco-friendly toiletries",
 * 			  "LED light bulbs",
 * 			  "Secured parking",
 * 			  "Secured parking",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Wheelchair-accessible concierge desk",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible meeting spaces/business center",
 * 			  "Wheelchair-accessible on-site restaurant",
 * 			  "Well-lit path to entrance"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "4",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 68758640,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1100/1087/fa911a49_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1100/1087/d4f08ef1_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1100/1087/469af8d8_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1100/1087/05251453_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1100/1087/02419536_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Ramada by Wyndham Rochelle Park Near Paramus",
 * 			"distance": "",
 * 			"latitude": "40.9186",
 * 			"longitude": "-74.085068",
 * 			"rating": "2",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "ATM/banking",
 * 			  "Conference space",
 * 			  "Laundry facilities",
 * 			  "Multilingual staff",
 * 			  "24-hour front desk",
 * 			  "Business center",
 * 			  "Smoke-free property",
 * 			  "Free WiFi",
 * 			  "Number of restaurants - 1",
 * 			  "Conference space size (feet) - 2100",
 * 			  "Conference space size (meters) - 195",
 * 			  "Number of meeting rooms - 1",
 * 			  "Free self parking",
 * 			  "Computer station",
 * 			  "Number of bars/lounges - 1",
 * 			  "Vending machine",
 * 			  "LED light bulbs",
 * 			  "Recycling",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Change of towels (on request)",
 * 			  "Change of bed sheets (on request)",
 * 			  "Guest education on local ecosystems and culture",
 * 			  "Energy-saving switches",
 * 			  "At least 80% of all lighting comes from LEDs"
 * 			},
 * 			"giata_destination": "Rochelle Park",
 * 			"user_rating": "2",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 48395644,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1700/1639/ad0d285d_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1700/1639/c09bc283_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1700/1639/7745246e_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1700/1639/c153784e_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1700/1639/ca159422_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Millennium Hilton New York One UN Plaza",
 * 			"distance": "",
 * 			"latitude": "40.750507",
 * 			"longitude": "-73.96978",
 * 			"rating": "4",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "ATM/banking",
 * 			  "Concierge services",
 * 			  "Conference space",
 * 			  "Breakfast available (surcharge)",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "Free newspapers in lobby",
 * 			  "24-hour front desk",
 * 			  "Porter/bellhop",
 * 			  "Express check-out",
 * 			  "Dry cleaning/laundry service",
 * 			  "Meeting rooms",
 * 			  "Wedding services",
 * 			  "Express check-in",
 * 			  "Tours/ticket assistance",
 * 			  "Free WiFi",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "Wheelchair accessible parking",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Conference space size (feet) - 7500",
 * 			  "Conference space size (meters) - 697",
 * 			  "Valet parking (surcharge)",
 * 			  "Number of coffee shops/cafes - 1",
 * 			  "Luggage storage",
 * 			  "24-hour fitness facilities",
 * 			  "Electric car charging station",
 * 			  "Housekeeping on request",
 * 			  "Ballroom",
 * 			  "Banquet hall",
 * 			  "Eco-friendly cleaning products provided",
 * 			  "Eco-friendly toiletries",
 * 			  "LED light bulbs",
 * 			  "Recycling",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Valet for wheelchair-equipped vehicle",
 * 			  "Wheelchair-accessible path to elevator",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible fitness center",
 * 			  "Wheelchair-accessible on-site restaurant",
 * 			  "Change of towels (on request)",
 * 			  "Change of bed sheets (on request)",
 * 			  "Well-lit path to entrance",
 * 			  "Stair-free path to entrance",
 * 			  "Vegetarian breakfast available",
 * 			  "Organic food",
 * 			  "Humane animal treatment",
 * 			  "Locally-owned & organized tours & activities",
 * 			  "Showcase for local artists",
 * 			  "Sustainability/community reinvestment (10% revenue or more)",
 * 			  "Guest education on local ecosystems and culture",
 * 			  "Double-glazing on all windows",
 * 			  "Locally-sourced food on site (80% or more)",
 * 			  "Energy-saving switches",
 * 			  "At least 80% of all lighting comes from LEDs",
 * 			  "Comprehensive food waste policy",
 * 			  "Vegan menu options available",
 * 			  "Vegetarian menu options available",
 * 			  "Comprehensive recycling policy",
 * 			  "No single-use plastic soda bottles",
 * 			  "No single-use plastic stirrers",
 * 			  "Biodegradable/compostable stirrers",
 * 			  "No single-use plastic straws",
 * 			  "Biodegradable/compostable straws",
 * 			  "No single-use plastic water bottles",
 * 			  "Reusable cups only",
 * 			  "Reusable tableware only",
 * 			  "Water-efficient showers only",
 * 			  "No accessible shuttle",
 * 			  "Number of accessible parking spaces - 2",
 * 			  "Registration desk height (inches) - 43",
 * 			  "Registration desk height (centimeters) - 109",
 * 			  "Elevator door width (inches) - 36",
 * 			  "Elevator door width (centimeters) - 91"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "4",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 97909073,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1700/1683/e15badb6_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1700/1683/830b87f4_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1700/1683/8c5c0fbb_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1700/1683/2ad462d2_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1700/1683/6f264f58_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "NH Collection New York Madison Avenue",
 * 			"distance": "",
 * 			"latitude": "40.750135",
 * 			"longitude": "-73.980818",
 * 			"rating": "4",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "Wheelchair accessible",
 * 			  "Concierge services",
 * 			  "Coffee/tea in common areas",
 * 			  "Breakfast available (surcharge)",
 * 			  "Laundry facilities",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "24-hour front desk",
 * 			  "Porter/bellhop",
 * 			  "Express check-out",
 * 			  "Dry cleaning/laundry service",
 * 			  "Limo or town car service available",
 * 			  "Smoke-free property",
 * 			  "Tours/ticket assistance",
 * 			  "Free WiFi",
 * 			  "Wheelchair accessible path of travel",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Number of meeting rooms - 1",
 * 			  "Number of bars/lounges - 1",
 * 			  "Luggage storage",
 * 			  "Offsite parking discounted rates available",
 * 			  "24-hour fitness facilities",
 * 			  "Water dispenser",
 * 			  "Housekeeping on request",
 * 			  "Eco-friendly cleaning products provided",
 * 			  "Eco-friendly toiletries",
 * 			  "LED light bulbs",
 * 			  "Recycling",
 * 			  "Reusable coffee/tea filters",
 * 			  "Eco-friendly cleaning products used",
 * 			  "Distance from property (ft) - 351",
 * 			  "Distance from property (meters) - 107",
 * 			  "Change of towels (on request)",
 * 			  "Change of bed sheets (on request)",
 * 			  "Vegetarian breakfast available",
 * 			  "Humane animal treatment",
 * 			  "Showcase for local artists",
 * 			  "Guest education on local ecosystems and culture",
 * 			  "Double-glazing on all windows",
 * 			  "Locally-sourced food on site (80% or more)",
 * 			  "Energy-saving switches",
 * 			  "At least 80% of all lighting comes from LEDs",
 * 			  "All property's electricity comes from renewable sources",
 * 			  "Comprehensive food waste policy",
 * 			  "Vegan menu options available",
 * 			  "Vegetarian menu options available",
 * 			  "Comprehensive recycling policy",
 * 			  "No single-use plastic soda bottles",
 * 			  "No single-use plastic stirrers",
 * 			  "Biodegradable/compostable stirrers",
 * 			  "No single-use plastic straws",
 * 			  "Biodegradable/compostable straws",
 * 			  "No single-use plastic water bottles",
 * 			  "Reusable cups only",
 * 			  "Reusable tableware only",
 * 			  "Water-efficient showers only",
 * 			  "Water-efficient toilets only",
 * 			  "Water dispenser use by guests actively encouraged"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "4",
 * 			"weight": 3316
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 45745986,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1900/1891/120d11de_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1900/1891/9ae03761_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1900/1891/a21310c8_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1900/1891/78ab7f97_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/1900/1891/c67c1efc_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "La Quinta Inn & Suites by Wyndham Secaucus Meadowlands",
 * 			"distance": "",
 * 			"latitude": "40.790325",
 * 			"longitude": "-74.049284",
 * 			"rating": "3",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "ATM/banking",
 * 			  "Concierge services",
 * 			  "Conference space",
 * 			  "Laundry facilities",
 * 			  "Television in common areas",
 * 			  "Free breakfast",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "24-hour front desk",
 * 			  "Business center",
 * 			  "Express check-out",
 * 			  "Meeting rooms",
 * 			  "Smoke-free property",
 * 			  "Tours/ticket assistance",
 * 			  "Free WiFi",
 * 			  "Wheelchair accessible path of travel",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "Wheelchair accessible parking",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Braille or raised signage",
 * 			  "Conference space size (feet) - 10000",
 * 			  "Conference space size (meters) - 929",
 * 			  "Number of indoor pools - 1",
 * 			  "Conference center",
 * 			  "Free self parking",
 * 			  "Computer station",
 * 			  "Daily",
 * 			  "Luggage storage",
 * 			  "Pool sun loungers",
 * 			  "Free continental breakfast",
 * 			  "Housekeeping on request",
 * 			  "Covered parking",
 * 			  "Uncovered parking",
 * 			  "Off-street parking",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Wheelchair-accessible public washroom",
 * 			  "Wheelchair-accessible van parking",
 * 			  "Wheelchair-accessible path to elevator",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible pool",
 * 			  "Wheelchair-accessible fitness center",
 * 			  "Wheelchair-accessible meeting spaces/business center",
 * 			  "Visual alarms in hallways",
 * 			  "Handrails in stairways",
 * 			  "Wheelchairs available on site",
 * 			  "Change of towels (on request)",
 * 			  "Change of bed sheets (on request)",
 * 			  "Well-lit path to entrance",
 * 			  "Stair-free path to entrance",
 * 			  "Pool hoist on site"
 * 			},
 * 			"giata_destination": "Secaucus",
 * 			"user_rating": "3",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 91553837,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2600/2591/a11959c2_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2600/2591/a25ad2c8_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2600/2591/786f3267_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2600/2591/7ace9eb7_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2600/2591/d3c11d5a_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Courtyard by Marriott Lyndhurst Meadowlands",
 * 			"distance": "",
 * 			"latitude": "40.809522",
 * 			"longitude": "-74.10402",
 * 			"rating": "3",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "Gift shops or newsstand",
 * 			  "Conference space",
 * 			  "Downhill skiing nearby",
 * 			  "Bicycle rentals nearby",
 * 			  "Hiking/biking trails nearby",
 * 			  "Breakfast available (surcharge)",
 * 			  "Laundry facilities",
 * 			  "Television in common areas",
 * 			  "Garden",
 * 			  "Safe-deposit box at front desk",
 * 			  "Picnic area",
 * 			  "24-hour front desk",
 * 			  "Express check-out",
 * 			  "Dry cleaning/laundry service",
 * 			  "Meeting rooms",
 * 			  "Smoke-free property",
 * 			  "Snowboarding nearby",
 * 			  "Free WiFi",
 * 			  "Wheelchair accessible path of travel",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "Wheelchair accessible parking",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Braille or raised signage",
 * 			  "Number of restaurants - 1",
 * 			  "24-hour business center",
 * 			  "Conference space size (feet) - 2196",
 * 			  "Conference space size (meters) - 204",
 * 			  "Number of meeting rooms - 6",
 * 			  "Snack bar/deli",
 * 			  "Helicopter/airplane tours on site",
 * 			  "Free self parking",
 * 			  "Number of bars/lounges - 1",
 * 			  "Segway rental/tour nearby",
 * 			  "Number of coffee shops/cafes - 1",
 * 			  "Banquet hall",
 * 			  "Fully fenced",
 * 			  "Uncovered parking",
 * 			  "Outdoor furniture",
 * 			  "Health or beauty spa nearby",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Wheelchair-accessible public washroom",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible fitness center",
 * 			  "Wheelchair-accessible meeting spaces/business center",
 * 			  "Wheelchair-accessible on-site restaurant",
 * 			  "Wheelchair-accessible lounge",
 * 			  "Visual alarms in hallways",
 * 			  "Change of towels (on request)",
 * 			  "Change of bed sheets (on request)",
 * 			  "Coworking spaces",
 * 			  "Well-lit path to entrance"
 * 			},
 * 			"giata_destination": "Lyndhurst",
 * 			"user_rating": "3",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 46472560,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2800/2714/1b8cafe9_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2800/2714/4ab2e0c8_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2800/2714/b1e7997f_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2800/2714/40d7155d_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2800/2714/1db3672b_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Park Lane New York",
 * 			"distance": "",
 * 			"latitude": "40.76522",
 * 			"longitude": "-73.97516",
 * 			"rating": "4.5",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Concierge services",
 * 			  "Conference space",
 * 			  "Bicycle rentals nearby",
 * 			  "Fireplace in lobby",
 * 			  "Breakfast available (surcharge)",
 * 			  "Garden",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "24-hour front desk",
 * 			  "Business center",
 * 			  "Porter/bellhop",
 * 			  "Express check-out",
 * 			  "Dry cleaning/laundry service",
 * 			  "Smoke-free property",
 * 			  "Expedia Local Expert concierge",
 * 			  "Tours/ticket assistance",
 * 			  "Free WiFi",
 * 			  "Wheelchair accessible path of travel",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "Wheelchair accessible parking",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Braille or raised signage",
 * 			  "Number of restaurants - 2",
 * 			  "24-hour business center",
 * 			  "Conference space size (feet) - 1500",
 * 			  "Conference space size (meters) - 139",
 * 			  "Number of meeting rooms - 4",
 * 			  "Valet parking (surcharge)",
 * 			  "Computer station",
 * 			  "Number of bars/lounges - 1",
 * 			  "Number of coffee shops/cafes - 1",
 * 			  "Luggage storage",
 * 			  "24-hour fitness facilities",
 * 			  "Housekeeping on request",
 * 			  "Vegetable garden",
 * 			  "Ballroom",
 * 			  "Banquet hall",
 * 			  "Reception hall",
 * 			  "Eco-friendly cleaning products provided",
 * 			  "Eco-friendly toiletries",
 * 			  "LED light bulbs",
 * 			  "Recycling",
 * 			  "Horse riding nearby",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Wheelchair-accessible public washroom",
 * 			  "Wheelchair-accessible concierge desk",
 * 			  "Wheelchair-accessible van parking",
 * 			  "Valet for wheelchair-equipped vehicle",
 * 			  "Wheelchair-accessible path to elevator",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible fitness center",
 * 			  "Wheelchair-accessible meeting spaces/business center",
 * 			  "Wheelchair-accessible on-site restaurant",
 * 			  "Wheelchair-accessible lounge",
 * 			  "Visual alarms in hallways",
 * 			  "Handrails in stairways",
 * 			  "Wheelchairs available on site",
 * 			  "Change of towels (on request)",
 * 			  "Change of bed sheets (on request)",
 * 			  "Well-lit path to entrance",
 * 			  "Stair-free path to entrance",
 * 			  "Vegetarian breakfast available",
 * 			  "Organic food",
 * 			  "Double-glazing on all windows",
 * 			  "Locally-sourced food on site (80% or more)",
 * 			  "At least 80% of all lighting comes from LEDs",
 * 			  "Comprehensive food waste policy",
 * 			  "Vegan menu options available",
 * 			  "Vegetarian menu options available",
 * 			  "No single-use plastic soda bottles",
 * 			  "No single-use plastic stirrers",
 * 			  "Biodegradable/compostable stirrers",
 * 			  "No single-use plastic straws",
 * 			  "Biodegradable/compostable straws",
 * 			  "No single-use plastic water bottles",
 * 			  "Reusable cups only",
 * 			  "Reusable tableware only",
 * 			  "Water-efficient showers only"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "4.5",
 * 			"weight": 7615
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 83154855,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2900/2896/c12cbb32_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2900/2896/4ba5a76e_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2900/2896/78ac4e96_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2900/2896/344a3f66_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/2900/2896/bac4f3e7_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "New York LaGuardia Airport Marriott",
 * 			"distance": "",
 * 			"latitude": "40.768417",
 * 			"longitude": "-73.867602",
 * 			"rating": "3.5",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "Free airport transportation",
 * 			  "ATM/banking",
 * 			  "Gift shops or newsstand",
 * 			  "Conference space",
 * 			  "Golfing nearby",
 * 			  "Hiking/biking trails nearby",
 * 			  "Breakfast available (surcharge)",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "Free newspapers in lobby",
 * 			  "24-hour front desk",
 * 			  "Business center",
 * 			  "Porter/bellhop",
 * 			  "Express check-out",
 * 			  "Dry cleaning/laundry service",
 * 			  "Smoke-free property",
 * 			  "Wedding services",
 * 			  "Free WiFi",
 * 			  "Free wired internet",
 * 			  "Wheelchair accessible path of travel",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "Wheelchair accessible parking",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Braille or raised signage",
 * 			  "Number of restaurants - 1",
 * 			  "Conference space size (feet) - 12845",
 * 			  "Conference space size (meters) - 1193",
 * 			  "Number of meeting rooms - 17",
 * 			  "Snack bar/deli",
 * 			  "Parking (limited spaces)",
 * 			  "Self parking (surcharge)",
 * 			  "Luggage storage",
 * 			  "24-hour fitness facilities",
 * 			  "Ballroom",
 * 			  "Wheelchair-accessible van parking",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible fitness center",
 * 			  "Wheelchair-accessible meeting spaces/business center",
 * 			  "Wheelchair-accessible on-site restaurant",
 * 			  "Visual alarms in hallways"
 * 			},
 * 			"giata_destination": "East Elmhurst",
 * 			"user_rating": "3.5",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 61248640,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3200/3129/4b7210dd_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3200/3129/75558269_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3200/3129/e674dbda_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3200/3129/b784f581_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3200/3129/4a49258d_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Hilton Meadowlands",
 * 			"distance": "",
 * 			"latitude": "40.8053",
 * 			"longitude": "-74.07808",
 * 			"rating": "3.5",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "ATM/banking",
 * 			  "Concierge services",
 * 			  "Gift shops or newsstand",
 * 			  "Conference space",
 * 			  "Golfing nearby",
 * 			  "Breakfast available (surcharge)",
 * 			  "Laundry facilities",
 * 			  "Television in common areas",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "24-hour front desk",
 * 			  "Porter/bellhop",
 * 			  "Express check-out",
 * 			  "Dry cleaning/laundry service",
 * 			  "Limo or town car service available",
 * 			  "Smoke-free property",
 * 			  "Wedding services",
 * 			  "Free WiFi",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "Wheelchair accessible parking",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Braille or raised signage",
 * 			  "Number of restaurants - 1",
 * 			  "Conference space size (feet) - 30000",
 * 			  "Conference space size (meters) - 2787",
 * 			  "Number of meeting rooms - 29",
 * 			  "Conference center",
 * 			  "Parking (limited spaces)",
 * 			  "Bicycle rentals on site",
 * 			  "Self parking (surcharge)",
 * 			  "Computer station",
 * 			  "Number of bars/lounges - 1",
 * 			  "Number of coffee shops/cafes - 1",
 * 			  "Luggage storage",
 * 			  "24-hour fitness facilities",
 * 			  "Electric car charging station",
 * 			  "Housekeeping on request",
 * 			  "Vegetable garden",
 * 			  "Ballroom",
 * 			  "Reception hall",
 * 			  "Vending machine",
 * 			  "Eco-friendly cleaning products provided",
 * 			  "Eco-friendly toiletries",
 * 			  "LED light bulbs",
 * 			  "Recycling",
 * 			  "Grey water recycling system",
 * 			  "Off-street parking",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Wheelchair-accessible public washroom",
 * 			  "Wheelchair-accessible concierge desk",
 * 			  "Wheelchair-accessible van parking",
 * 			  "Wheelchair-accessible path to elevator",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible fitness center",
 * 			  "Wheelchair-accessible on-site restaurant",
 * 			  "Wheelchair-accessible lounge",
 * 			  "Change of towels (on request)",
 * 			  "Change of bed sheets (on request)",
 * 			  "Well-lit path to entrance",
 * 			  "Stair-free path to entrance",
 * 			  "Vegetarian breakfast available",
 * 			  "Organic food",
 * 			  "Humane animal treatment",
 * 			  "Sustainability/community reinvestment (10% revenue or more)",
 * 			  "Locally-sourced food on site (80% or more)",
 * 			  "Energy-saving switches",
 * 			  "At least 80% of all lighting comes from LEDs",
 * 			  "All property's electricity comes from renewable sources",
 * 			  "Comprehensive food waste policy",
 * 			  "Vegan menu options available",
 * 			  "Vegetarian menu options available",
 * 			  "Comprehensive recycling policy",
 * 			  "No single-use plastic soda bottles",
 * 			  "No single-use plastic stirrers",
 * 			  "Biodegradable/compostable stirrers",
 * 			  "No single-use plastic straws",
 * 			  "Biodegradable/compostable straws",
 * 			  "No single-use plastic water bottles",
 * 			  "Reusable cups only",
 * 			  "Reusable tableware only",
 * 			  "Water-efficient showers only"
 * 			},
 * 			"giata_destination": "East Rutherford",
 * 			"user_rating": "3.5",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 78039564,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3229/cb82a2bd_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3229/03b60d34_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3229/9c5626c9_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3229/59792f88_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3229/8b2c8e4c_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Kixby",
 * 			"distance": "",
 * 			"latitude": "40.749974",
 * 			"longitude": "-73.986086",
 * 			"rating": "4",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "Coffee/tea in common areas",
 * 			  "Breakfast available (surcharge)",
 * 			  "Garden",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "24-hour front desk",
 * 			  "Porter/bellhop",
 * 			  "Dry cleaning/laundry service",
 * 			  "Smoke-free property",
 * 			  "Free WiFi",
 * 			  "Wheelchair accessible path of travel",
 * 			  "Assistive listening devices available",
 * 			  "Number of restaurants - 1",
 * 			  "Computer station",
 * 			  "Rooftop terrace",
 * 			  "Number of bars/lounges - 2",
 * 			  "Luggage storage",
 * 			  "Offsite parking discounted rates available",
 * 			  "Terrace",
 * 			  "Electric car charging station",
 * 			  "Vegetable garden",
 * 			  "Eco-friendly toiletries",
 * 			  "Grey water recycling system",
 * 			  "Distance from property (ft) - 98",
 * 			  "Distance from property (meters) - 30",
 * 			  "Lot hours - 24 hours",
 * 			  "Health or beauty spa nearby",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Wheelchair-accessible public washroom",
 * 			  "Wheelchair-accessible path to elevator",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible on-site restaurant",
 * 			  "Well-lit path to entrance",
 * 			  "Stair-free path to entrance",
 * 			  "Organic food",
 * 			  "Locally-sourced food on site (80% or more)"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "4",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 68514477,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3253/267c2dc4_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3253/9d3637f9_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3253/4c35cdda_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3253/0684dd58_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3253/1aface35_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "The Lowell",
 * 			"distance": "",
 * 			"latitude": "40.765866",
 * 			"longitude": "-73.969103",
 * 			"rating": "5",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "Wheelchair accessible",
 * 			  "Concierge services",
 * 			  "Bicycle rentals nearby",
 * 			  "Fireplace in lobby",
 * 			  "Hiking/biking trails nearby",
 * 			  "Breakfast available (surcharge)",
 * 			  "Library",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "Free newspapers in lobby",
 * 			  "24-hour front desk",
 * 			  "Porter/bellhop",
 * 			  "Dry cleaning/laundry service",
 * 			  "Limo or town car service available",
 * 			  "Meeting rooms",
 * 			  "Smoke-free property",
 * 			  "Tours/ticket assistance",
 * 			  "Free WiFi",
 * 			  "Free wired internet",
 * 			  "Wheelchair accessible path of travel",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Number of restaurants - 4",
 * 			  "24-hour business center",
 * 			  "Valet parking (surcharge)",
 * 			  "Number of bars/lounges - 1",
 * 			  "Luggage storage",
 * 			  "Terrace",
 * 			  "Babysitting or childcare (surcharge)",
 * 			  "Banquet hall",
 * 			  "Wheelchair accessible (may have limitations)"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "5",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 88914753,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3281/ad5498ef_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3281/c931aa81_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3281/e0a67386_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3281/f380b918_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3300/3281/6032c8e1_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Renaissance New York Times Square Hotel",
 * 			"distance": "",
 * 			"latitude": "40.75968",
 * 			"longitude": "-73.9843",
 * 			"rating": "4",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "Concierge services",
 * 			  "Conference space",
 * 			  "Hiking/biking trails nearby",
 * 			  "Television in common areas",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "Free newspapers in lobby",
 * 			  "24-hour front desk",
 * 			  "Business center",
 * 			  "Dry cleaning/laundry service",
 * 			  "Limo or town car service available",
 * 			  "Smoke-free property",
 * 			  "Wedding services",
 * 			  "Free WiFi",
 * 			  "Wheelchair accessible path of travel",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Braille or raised signage",
 * 			  "Number of restaurants - 1",
 * 			  "Conference space size (feet) - 1591",
 * 			  "Conference space size (meters) - 148",
 * 			  "Number of meeting rooms - 5",
 * 			  "Self parking (surcharge)",
 * 			  "Valet parking (surcharge)",
 * 			  "Computer station",
 * 			  "Number of bars/lounges - 1",
 * 			  "24-hour fitness facilities",
 * 			  "Electric car charging station",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible fitness center",
 * 			  "Wheelchair-accessible meeting spaces/business center",
 * 			  "Wheelchair-accessible on-site restaurant",
 * 			  "Visual alarms in hallways",
 * 			  "Food and water bowls",
 * 			  "No accessible shuttle"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "4",
 * 			"weight": 3270
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 73465393,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3700/3670/f27a1835_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3700/3670/e0f88adb_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3700/3670/307dc267_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3700/3670/64cb0115_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/3700/3670/2d02c99a_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Empire Hotel",
 * 			"distance": "",
 * 			"latitude": "40.771583",
 * 			"longitude": "-73.982599",
 * 			"rating": "4",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "Concierge services",
 * 			  "Garden",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "24-hour front desk",
 * 			  "Porter/bellhop",
 * 			  "Dry cleaning/laundry service",
 * 			  "Limo or town car service available",
 * 			  "Swimming pool",
 * 			  "Meeting rooms",
 * 			  "Smoke-free property",
 * 			  "Outdoor seasonal pool",
 * 			  "Free WiFi",
 * 			  "Wheelchair accessible path of travel",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Braille or raised signage",
 * 			  "Number of restaurants - 1",
 * 			  "Self parking (surcharge)",
 * 			  "Valet parking (surcharge)",
 * 			  "Computer station",
 * 			  "Rooftop terrace",
 * 			  "Number of bars/lounges - 1",
 * 			  "Luggage storage",
 * 			  "Pool sun loungers",
 * 			  "Terrace",
 * 			  "Electric car charging station",
 * 			  "Housekeeping on request",
 * 			  "Vegetable garden",
 * 			  "Eco-friendly cleaning products provided",
 * 			  "Eco-friendly toiletries",
 * 			  "LED light bulbs",
 * 			  "Recycling",
 * 			  "Grey water recycling system",
 * 			  "Covered parking",
 * 			  "Secured parking",
 * 			  "Covered parking",
 * 			  "Secured parking",
 * 			  "Health or beauty spa nearby",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Wheelchair-accessible public washroom",
 * 			  "Wheelchair-accessible concierge desk",
 * 			  "Valet for wheelchair-equipped vehicle",
 * 			  "Wheelchair-accessible path to elevator",
 * 			  "Wheelchair-accessible lounge",
 * 			  "Visual alarms in hallways",
 * 			  "Food and water bowls",
 * 			  "Change of towels (on request)",
 * 			  "Change of bed sheets (on request)",
 * 			  "Coworking spaces",
 * 			  "Stair-free path to entrance",
 * 			  "Vegetarian breakfast available",
 * 			  "Organic food",
 * 			  "Humane animal treatment",
 * 			  "Locally-owned & organized tours & activities",
 * 			  "Showcase for local artists",
 * 			  "Sustainability/community reinvestment (10% revenue or more)",
 * 			  "Guest education on local ecosystems and culture",
 * 			  "Double-glazing on all windows",
 * 			  "Locally-sourced food on site (80% or more)",
 * 			  "Energy-saving switches",
 * 			  "At least 80% of all lighting comes from LEDs",
 * 			  "Comprehensive food waste policy",
 * 			  "Vegan menu options available",
 * 			  "Vegetarian menu options available",
 * 			  "Comprehensive recycling policy",
 * 			  "No single-use plastic soda bottles",
 * 			  "No single-use plastic stirrers",
 * 			  "Biodegradable/compostable stirrers",
 * 			  "No single-use plastic straws",
 * 			  "Biodegradable/compostable straws",
 * 			  "No single-use plastic water bottles",
 * 			  "Reusable cups only",
 * 			  "Reusable tableware only",
 * 			  "Water-efficient showers only",
 * 			  "No accessible shuttle",
 * 			  "Smooth flooring in public areas",
 * 			  "Thin carpet in public areas",
 * 			  "Area rugs in public areas",
 * 			  "Elevator door width (inches) - 50",
 * 			  "Elevator door width (centimeters) - 127"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "4",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 72932717,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4100/4085/cbb2bcb8_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4100/4085/cb42064c_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4100/4085/8a5332ae_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4100/4085/1e5ab826_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4100/4085/efede059_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Off Soho Suites Hotel",
 * 			"distance": "",
 * 			"latitude": "40.721325",
 * 			"longitude": "-73.992657",
 * 			"rating": "2",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "Hair salon",
 * 			  "ATM/banking",
 * 			  "Concierge services",
 * 			  "Bicycle rentals nearby",
 * 			  "Fireplace in lobby",
 * 			  "Laundry facilities",
 * 			  "Television in common areas",
 * 			  "Library",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "Free newspapers in lobby",
 * 			  "24-hour front desk",
 * 			  "Business center",
 * 			  "Porter/bellhop",
 * 			  "Dry cleaning/laundry service",
 * 			  "Limo or town car service available",
 * 			  "Designated smoking areas",
 * 			  "Grocery/convenience store",
 * 			  "Free WiFi",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Braille or raised signage",
 * 			  "24-hour business center",
 * 			  "Luggage storage",
 * 			  "Offsite parking discounted rates available",
 * 			  "Art gallery on site",
 * 			  "Vending machine",
 * 			  "Street parking",
 * 			  "Distance from property (ft) - 3281",
 * 			  "Distance from property (km) - 1",
 * 			  "Distance from property (miles) - 1",
 * 			  "Lot hours - 24 hours",
 * 			  "Coin laundry on site",
 * 			  "Wheelchair accessible (may have limitations)"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "2",
 * 			"weight": 2342
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 37305666,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4200/4164/675037ae_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4200/4164/be69ccd8_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4200/4164/9111c8a7_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4200/4164/3631d397_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4200/4164/79334e5a_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Park Central Hotel New York",
 * 			"distance": "",
 * 			"latitude": "40.76452",
 * 			"longitude": "-73.98078",
 * 			"rating": "4",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "ATM/banking",
 * 			  "Concierge services",
 * 			  "Conference space",
 * 			  "Bicycle rentals nearby",
 * 			  "Coffee/tea in common areas",
 * 			  "Hiking/biking trails nearby",
 * 			  "Breakfast available (surcharge)",
 * 			  "Laundry facilities",
 * 			  "Safe-deposit box at front desk",
 * 			  "Multilingual staff",
 * 			  "Free newspapers in lobby",
 * 			  "24-hour front desk",
 * 			  "Business center",
 * 			  "Porter/bellhop",
 * 			  "Express check-out",
 * 			  "Dry cleaning/laundry service",
 * 			  "Limo or town car service available",
 * 			  "Meeting rooms",
 * 			  "Smoke-free property",
 * 			  "Expedia Local Expert concierge",
 * 			  "Tours/ticket assistance",
 * 			  "Free WiFi",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Braille or raised signage",
 * 			  "Number of restaurants - 1",
 * 			  "24-hour business center",
 * 			  "Snack bar/deli",
 * 			  "Bicycle rentals on site",
 * 			  "Valet parking (surcharge)",
 * 			  "Computer station",
 * 			  "Number of bars/lounges - 1",
 * 			  "Number of coffee shops/cafes - 1",
 * 			  "Luggage storage",
 * 			  "Boat tours nearby",
 * 			  "24-hour health club",
 * 			  "Eco-friendly toiletries",
 * 			  "Recycling",
 * 			  "Wheelchair accessible (may have limitations)"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "4",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 73356135,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4700/4608/e425d85f_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4700/4608/6eeabfe3_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4700/4608/f61f4130_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4700/4608/9141ea04_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4700/4608/40e2c8fe_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "The Hotel @ Times Square",
 * 			"distance": "",
 * 			"latitude": "40.75727",
 * 			"longitude": "-73.98118",
 * 			"rating": "3",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "Concierge services",
 * 			  "Safe-deposit box at front desk",
 * 			  "Free newspapers in lobby",
 * 			  "24-hour front desk",
 * 			  "Dry cleaning/laundry service",
 * 			  "Designated smoking areas",
 * 			  "Tours/ticket assistance",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "24-hour business center",
 * 			  "Luggage storage",
 * 			  "Offsite parking discounted rates available",
 * 			  "24-hour fitness facilities",
 * 			  "Health or beauty spa nearby",
 * 			  "Wheelchair accessible (may have limitations)"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "3",
 * 			"weight": 0
 * 		  },
 * 		  {
 * 			"giata_hotel_code": 61596742,
 * 			"images": {
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4900/4818/97794606_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4900/4818/acbc4d8a_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4900/4818/8c30fa7a_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4900/4818/72145646_b.jpg",
 * 			  "https://i.travelapi.com/lodging/1000000/10000/4900/4818/35d1b430_b.jpg"
 * 			},
 * 			"description": "",
 * 			"hotel_name": "Lotte New York Palace",
 * 			"distance": "",
 * 			"latitude": "40.758229",
 * 			"longitude": "-73.974529",
 * 			"rating": "4.5",
 * 			"amenities": {
 * 			  "Elevator",
 * 			  "Fitness facilities",
 * 			  "Wheelchair accessible",
 * 			  "ATM/banking",
 * 			  "Concierge services",
 * 			  "Gift shops or newsstand",
 * 			  "Shopping on site",
 * 			  "Conference space",
 * 			  "Golfing nearby",
 * 			  "Coffee/tea in common areas",
 * 			  "Hiking/biking trails nearby",
 * 			  "Breakfast available (surcharge)",
 * 			  "Laundry facilities",
 * 			  "Garden",
 * 			  "Health club",
 * 			  "Safe-deposit box at front desk",
 * 			  "Spa services on site",
 * 			  "Multilingual staff",
 * 			  "Free newspapers in lobby",
 * 			  "24-hour front desk",
 * 			  "Business center",
 * 			  "Porter/bellhop",
 * 			  "Express check-out",
 * 			  "Dry cleaning/laundry service",
 * 			  "Limo or town car service available",
 * 			  "Full-service spa",
 * 			  "Spa treatment room(s)",
 * 			  "Meeting rooms",
 * 			  "Steam room",
 * 			  "Smoke-free property",
 * 			  "Wedding services",
 * 			  "Tours/ticket assistance",
 * 			  "WiFi (surcharge)",
 * 			  "Wired internet access - surcharge",
 * 			  "Wheelchair accessible path of travel",
 * 			  "Accessible bathroom (in select rooms)",
 * 			  "Roll-in shower (in select rooms)",
 * 			  "Wheelchair accessible parking",
 * 			  "In-room accessibility (in select rooms)",
 * 			  "Assistive listening devices available",
 * 			  "Braille or raised signage",
 * 			  "Number of restaurants - 1",
 * 			  "Conference center",
 * 			  "Snack bar/deli",
 * 			  "Free bicycles on site",
 * 			  "Valet parking (surcharge)",
 * 			  "Number of bars/lounges - 1",
 * 			  "Number of coffee shops/cafes - 1",
 * 			  "Luggage storage",
 * 			  "Babysitting or childcare (surcharge)",
 * 			  "Supervised childcare/activities (surcharge)",
 * 			  "Ballroom",
 * 			  "Banquet hall",
 * 			  "Reception hall",
 * 			  "Eco-friendly toiletries",
 * 			  "Covered parking",
 * 			  "Secured parking",
 * 			  "Wheelchair accessible (may have limitations)",
 * 			  "Wheelchair-accessible public washroom",
 * 			  "Wheelchair-accessible concierge desk",
 * 			  "Wheelchair-accessible van parking",
 * 			  "Valet for wheelchair-equipped vehicle",
 * 			  "Wheelchair-accessible registration desk",
 * 			  "Wheelchair-accessible spa",
 * 			  "Wheelchair-accessible pool",
 * 			  "Wheelchair-accessible fitness center",
 * 			  "Wheelchair-accessible meeting spaces/business center",
 * 			  "Wheelchair-accessible on-site restaurant",
 * 			  "Wheelchair-accessible lounge"
 * 			},
 * 			"giata_destination": "New York",
 * 			"user_rating": "4.5",
 * 			"weight": 4502
 * 		  }
 * 		}
 * 	  }
 * 	},
 * 	"message": "success"
 *   }
 * )
 */




class ContentSearchResponse
{
}
